module.exports = {
    events: [
        {
            id: 1,
            name: "Ed Sheer 01",
            event_date: "2022-05-25T15:40:00",
            image_url: "https://images.sk-static.com/images/media/profile_images/artists/2083334/huge_avatar",
            created_at: "2022-05-25T16:20:10",
            available_spots: 10,
            price: 110
        },
        {
            id: 2,
            name: "Ed Sheran 02",
            event_date: "2022-05-26T16:20:00",
            image_url: "https://images.sk-static.com/images/media/profile_images/artists/2083334/huge_avatar",
            created_at: "2022-05-26T16:20:10",
            available_spots: 22,
            price: 220
        },
        {
            id: 3,
            name: "Ed Heeran 03",
            event_date: "2022-05-27T16:30:00",
            image_url: "https://images.sk-static.com/images/media/profile_images/artists/2083334/huge_avatar",
            created_at: "2022-05-27T16:20:10",
            available_spots: 30,
            price: 330
        }
    ],
    spots: [
        { id: 1, name: "A1", status: 'available', event_id: 1 },
        { id: 2, name: "A2", status: 'available', event_id: 1 },
        { id: 3, name: "A3", status: 'available', event_id: 1 },
        { id: 4, name: "A4", status: 'available', event_id: 1 },
        { id: 5, name: "A5", status: 'available', event_id: 1 },
        { id: 6, name: "B1", status: 'available', event_id: 1 },
        { id: 7, name: "B2", status: 'available', event_id: 1 },
        { id: 8, name: "B3", status: 'available', event_id: 1 },
        { id: 9, name: "B4", status: 'available', event_id: 1 },
        { id: 10, name: "B5", status: 'available', event_id: 1 },

        { id: 1, name: "A1", status: 'available', event_id: 2 },
        { id: 2, name: "A2", status: 'available', event_id: 2 },
        { id: 3, name: "A3", status: 'available', event_id: 2 },
        { id: 4, name: "A4", status: 'available', event_id: 2 },
        { id: 5, name: "A5", status: 'available', event_id: 2 },
        { id: 6, name: "A6", status: 'available', event_id: 2 },
        { id: 7, name: "A7", status: 'available', event_id: 2 },
        { id: 8, name: "A8", status: 'available', event_id: 2 },
        { id: 9, name: "A9", status: 'available', event_id: 2 },
        { id: 10, name: "A10", status: 'available', event_id: 2 },
        { id: 11, name: "B1", status: 'available', event_id: 2 },
        { id: 12, name: "B2", status: 'available', event_id: 2 },
        { id: 13, name: "B3", status: 'available', event_id: 2 },
        { id: 14, name: "B4", status: 'available', event_id: 2 },
        { id: 15, name: "B5", status: 'available', event_id: 2 },
        { id: 16, name: "B6", status: 'available', event_id: 2 },
        { id: 17, name: "B7", status: 'available', event_id: 2 },
        { id: 18, name: "B8", status: 'available', event_id: 2 },
        { id: 19, name: "B9", status: 'available', event_id: 2 },
        { id: 20, name: "B10", status: 'available', event_id: 2 },

        { id: 1, name: "A1", status: 'available', event_id: 3 },
        { id: 2, name: "A2", status: 'available', event_id: 3 },
        { id: 3, name: "A3", status: 'available', event_id: 3 },
        { id: 4, name: "A4", status: 'available', event_id: 3 },
        { id: 5, name: "A5", status: 'available', event_id: 3 },
        { id: 6, name: "A6", status: 'available', event_id: 3 },
        { id: 7, name: "A7", status: 'available', event_id: 3 },
        { id: 8, name: "A8", status: 'available', event_id: 3 },
        { id: 9, name: "A9", status: 'available', event_id: 3 },
        { id: 10, name: "A10", status: 'available', event_id: 3 },
        { id: 11, name: "A11", status: 'available', event_id: 3 },
        { id: 12, name: "A12", status: 'available', event_id: 3 },
        { id: 13, name: "A13", status: 'available', event_id: 3 },
        { id: 14, name: "A14", status: 'available', event_id: 3 },
        { id: 15, name: "A15", status: 'available', event_id: 3 },
        { id: 16, name: "B1", status: 'available', event_id: 3 },
        { id: 17, name: "B2", status: 'available', event_id: 3 },
        { id: 18, name: "B3", status: 'available', event_id: 3 },
        { id: 19, name: "B4", status: 'available', event_id: 3 },
        { id: 20, name: "B5", status: 'available', event_id: 3 },
        { id: 21, name: "B6", status: 'available', event_id: 3 },
        { id: 22, name: "B7", status: 'available', event_id: 3 },
        { id: 23, name: "B8", status: 'available', event_id: 3 },
        { id: 24, name: "B9", status: 'available', event_id: 3 },
        { id: 25, name: "B10", status: 'available', event_id: 3 },
        { id: 26, name: "B11", status: 'available', event_id: 3 },
        { id: 27, name: "B12", status: 'available', event_id: 3 },
        { id: 28, name: "B13", status: 'available', event_id: 3 },
        { id: 29, name: "B14", status: 'available', event_id: 3 },
        { id: 30, name: "B15", status: 'available', event_id: 3 },

    ]
}